//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlotokingUIAuto {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestDataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestDataResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlotokingUIAuto.TestDataResource", typeof(TestDataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 380505640967.
        /// </summary>
        internal static string FacebookLogin {
            get {
                return ResourceManager.GetString("FacebookLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на qweasdzxcvvv.
        /// </summary>
        internal static string FacebookPass {
            get {
                return ResourceManager.GetString("FacebookPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dijust.test@gmail.com.
        /// </summary>
        internal static string GoogleLogin {
            get {
                return ResourceManager.GetString("GoogleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на qweasdzxcvvv.
        /// </summary>
        internal static string GooglePass {
            get {
                return ResourceManager.GetString("GooglePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dijust.test@mail.ru.
        /// </summary>
        internal static string MailRuLogin {
            get {
                return ResourceManager.GetString("MailRuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на qweasdzxcvvv.
        /// </summary>
        internal static string MailRUPass {
            get {
                return ResourceManager.GetString("MailRUPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://slotoking.com.
        /// </summary>
        internal static string MainPageURL {
            get {
                return ResourceManager.GetString("MainPageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на amys1@mail.ru.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 380505640967.
        /// </summary>
        internal static string OkLogin {
            get {
                return ResourceManager.GetString("OkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на qweasdzxcvvv.
        /// </summary>
        internal static string OKPass {
            get {
                return ResourceManager.GetString("OKPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 123456.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на stage.
        /// </summary>
        internal static string stageLogin {
            get {
                return ResourceManager.GetString("stageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ao4F1DAixL7G.
        /// </summary>
        internal static string stagePassword {
            get {
                return ResourceManager.GetString("stagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на amys@cleack.com.
        /// </summary>
        internal static string TestRestoreUserEmail {
            get {
                return ResourceManager.GetString("TestRestoreUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 500508111.
        /// </summary>
        internal static string TestRestoreUserPhone {
            get {
                return ResourceManager.GetString("TestRestoreUserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на amys1111@mail.ru.
        /// </summary>
        internal static string TestUserEmail {
            get {
                return ResourceManager.GetString("TestUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a.m-y_s@mail.ru.
        /// </summary>
        internal static string TestUserEmailWithSymbols {
            get {
                return ResourceManager.GetString("TestUserEmailWithSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 509991231.
        /// </summary>
        internal static string TestUserPhone {
            get {
                return ResourceManager.GetString("TestUserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dijust.test@gmail.com.
        /// </summary>
        internal static string TwitterLogin {
            get {
                return ResourceManager.GetString("TwitterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на qweasdzxcvvv.
        /// </summary>
        internal static string TwitterPass {
            get {
                return ResourceManager.GetString("TwitterPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alex.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Schicklgruber.
        /// </summary>
        internal static string UserNickname {
            get {
                return ResourceManager.GetString("UserNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adolf.
        /// </summary>
        internal static string UserSurname {
            get {
                return ResourceManager.GetString("UserSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на +380505640967.
        /// </summary>
        internal static string VKLogin {
            get {
                return ResourceManager.GetString("VKLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на qweasdzxcvvv.
        /// </summary>
        internal static string VKPass {
            get {
                return ResourceManager.GetString("VKPass", resourceCulture);
            }
        }
    }
}
